### ISSUE TITLE
Normalize all paths for the input

### ISSUE THREAD

**Issue by pbelokon** [seog-jun/til-tool#6]
## Description 

As can be seen below when executing `` ts-node src/index.ts -i ``  with an absolute path program tries  to look for directory + path name which results in this ``'D:\\til-tool\\D:\\example'``

```js
D:\til-tool> ts-node src/index.ts -i D:\example 
Error: ENOENT: no such file or directory, scandir 'D:\til-tool\D:\example'
    at Object.readdirSync (node:fs:1452:3)
    at Object.module.exports.readDirectory (D:\til-tool\src\utility\readDirectory.ts:8:22)
    at Object.<anonymous> (D:\til-tool\src\index.ts:62:32)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (C:\Users\pavel\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\pavel\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\til-tool\\D:\\example'
```

**Comment by seog-jun** [comment]
Thanks for the feedback! This tool is basically designed to support 'Relative path" starting from the tool directory. I'll be refactoring this one when I have a chance. Thanks
